### ISSUE TITLE
Corriger les liens nécessitant un passage de paramètres

### ISSUE THREAD

**Issue by jplumez** [Ritou19/MovieApp#14]
Le code suivant :

```
<h:commandLink action="movieDetails">
      <h:outputText value="#{movie.name}" />
      <f:actionListener binding="#{movieDetailsBean.setMovie(movie)}" />
</h:commandLink>
```

n'est pas optimal. Que se passe-t-il si movie vaut null ? Le code movieDetails sera tout de même envoyé, la page movieDetails.xhtml va quand même être affichée, etc...

Alors qu'un lien de ce type :

`<h:commandLink value="#{movie.name}" action="#{movieDetailsBean.showMovie(movie)}" />`

Permet de renvoyer "movieDetails" si tout est OK, ou "error" si une erreur survient.

Nous vous suggérons de modifier vos lien.

**Comment by jeremybarfuss** [comment]
Résolu avec la pull request #21
