### ISSUE TITLE
Corriger la classe UniqueException

### ISSUE THREAD

**Issue by jplumez** [Ritou19/MovieApp#18]
Lorsque vous faites une exception personnalisée, on propose en général des constructeurs permettant de spécifier au moins un message.. et également une exception "mère". Cf les constructeurs par défaut de la classe Exception.

ET ON NE MET PAS UN SYSTEM.OUT DANS UNE APPLICATION WEB.

**Comment by jeremybarfuss** [comment]
Corrigé avec la pull request #23
